### PR TITLE
Added ActivityTotal section

### PR DESCRIPTION
**Pull request by bryanwong8**

### CODE REVIEW

**Review by srkirkland — COMMENTED** [review]
I see how the totals are being passed around but I'm not seeing where the form state is being stored.  Like at some point we are going to have to send a JSON blob to the server with all of the choices and totals, save that to a database, send a confirmation email with the quote, allow changes later if mistakes were made, etc.

**Comment by bryanwong8** [comment]
The Form state is in ActivityForm

**Comment by srkirkland** [comment]
@wongband I see in the `ActivityForm` component we keep the state of 3 numbers (the totals from each section), but I don't see where it is capturing the content of the individual items, or how it would handle if a new activity section was added (in addition to the "Apple Harvest" one)

**Comment by bryanwong8** [comment]
What do you mean by capturing the content of individual items?

**Comment by srkirkland** [comment]
@wongband I need to be able to have a JSON object which contains the info entered, like which labor did they select, how much time was in the hour box, what was the rate, etc.  For each item.  does that make sense?  I can show you on the mockup if you want

**Comment by bryanwong8** [comment]
Oh wait so you just need the JSON object for the info selected in the ActivityForm?

**Pull request closed without merging**
